### ISSUE TITLE
Make calls to the Instance Registry consistent with OpenAPI specification

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-webapp#18]
The REST-API of the Instance Registry server is specified in an OpenAPI specification file (here https://github.com/delphi-hub/delphi-registry/blob/master/OpenAPISpecification.yaml). The WebApp must be consistent with this specification when it registers / asks for an WebAPI instance. In order to do this, the respective calls with the BlockingHttpClient have to be adapted to the correct URLs. Also the parameters that are being sent need to be of the format specified by the file.

(*Opening the specification file in the editor on https://editor.swagger.io makes working with the it easier.*)

**Comment by sami-cseseu** [comment]
I wrote a request but couple of thing I need to mention.
1. Instance registry port number is 8085 which is similar to Webapp. I think we need to change the port number of the Webapp or Instance registry
2. In \register path ID should be filed up automatically by instance registry and what should be the    name not clear
3.There should be a \ping url so that we can check instance registry is active because Webapp can run without instance registry
4. Webapp will do a request to instance registry to save the info other than that is there any other relation between Webapp and instance registry?

**Comment by johannesduesing** [comment]
I'll try to answer that one by one :smile:  
1. Good point, i think we should change the port of the instance registry server to something that is not in use. @Ayybeeshafi can you implement this in the API specification as part of https://github.com/delphi-hub/delphi-registry/issues/6 ?
2. All the attributes of an 'Instance' that is specified in the file are optional. This means for registring you will specify all values *but* the ID, you can just leave it empty, and the Registry will assign an unique ID.
3. I don't think we need a /ping command, if the call to /register failes because of 'Connection refused', you do already know that the registry is not running.
4. The WebApp must do a call to /register on startup. It should also call /matchingInstance?ComponentType=WebAPI to get an instance of the WebAPI assigned, and use it's IP to actually connect to this WebAPI Instance. It should use /matchingResult to report whether the assigned WebAPI was reachable, and it should call /deregister on Shutdown

**Comment by Ayybeeshafi** [comment]
Sure. I will get it done.
